version: '3'
services:
  postgres:     
    image: postgres
    env_file: 
    - environment.env   
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
     - mynetwork
  app:
    build: ./
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    depends_on: 
      - postgres
    env_file: 
    - environment.env
volumes:
  db-data:

networks:
  mynetwork:
    driver: bridge


